export type TalentProfile = {
  id: number;
  kind: "persona" | "negocio";
  name: string;
  role: string;
  category: string;
  location: string;
  department: string;
  description: string;
  skills: string[];
  rating: number;
  reviews: number;
  verified?: boolean;
  available?: boolean;
  initials: string;
  accent: string;
  mapPosition: { x: number; y: number };
  coordinates: { lat: number; lng: number };
};

export const categories = ["Todos", "Diseño", "Tecnología", "Fotografía", "Gastronomía", "Artesanía", "Servicios"];

export const profiles: TalentProfile[] = [
  {
    id: 1,
    kind: "persona",
    name: "Andrea López",
    role: "Diseñadora de marca",
    category: "Diseño",
    location: "Managua",
    department: "Managua",
    description: "Creo identidades visuales, contenido para redes y piezas que ayudan a pequeños negocios a verse profesionales.",
    skills: ["Branding", "Social media", "Ilustración"],
    rating: 4.9,
    reviews: 31,
    verified: true,
    available: true,
    initials: "AL",
    accent: "linear-gradient(135deg, #071d36, #1f5b92)",
    mapPosition: { x: 51, y: 59 },
    coordinates: { lat: 12.11499, lng: -86.23617 },
  },
  {
    id: 2,
    kind: "persona",
    name: "Carlos Mena",
    role: "Desarrollador web",
    category: "Tecnología",
    location: "León",
    department: "León",
    description: "Desarrollo sitios web rápidos para emprendimientos, portafolios y comercios que quieren vender en línea.",
    skills: ["Web", "E-commerce", "Automatización"],
    rating: 4.8,
    reviews: 18,
    verified: true,
    available: true,
    initials: "CM",
    accent: "linear-gradient(135deg, #061a33, #174b80)",
    mapPosition: { x: 32, y: 46 },
    coordinates: { lat: 12.43556, lng: -86.87944 },
  },
  {
    id: 3,
    kind: "persona",
    name: "Valeria Ruiz",
    role: "Fotógrafa & creadora",
    category: "Fotografía",
    location: "Granada",
    department: "Granada",
    description: "Fotografía de producto, retratos y contenido audiovisual para marcas que quieren contar mejor su historia.",
    skills: ["Producto", "Retrato", "Video corto"],
    rating: 5,
    reviews: 24,
    verified: true,
    available: false,
    initials: "VR",
    accent: "linear-gradient(135deg, #15395f, #4e7ca8)",
    mapPosition: { x: 63, y: 65 },
    coordinates: { lat: 11.92988, lng: -85.95602 },
  },
  {
    id: 4,
    kind: "negocio",
    name: "Dulce Norte",
    role: "Repostería artesanal",
    category: "Gastronomía",
    location: "Estelí",
    department: "Estelí",
    description: "Postres, pasteles personalizados y mesas dulces hechas por un emprendimiento joven del norte del país.",
    skills: ["Pastelería", "Eventos", "Pedidos"],
    rating: 4.9,
    reviews: 42,
    verified: false,
    available: true,
    initials: "DN",
    accent: "linear-gradient(135deg, #0d2847, #315d89)",
    mapPosition: { x: 49, y: 29 },
    coordinates: { lat: 13.09185, lng: -86.35384 },
  },
  {
    id: 5,
    kind: "negocio",
    name: "Taller Güegüense",
    role: "Artesanía contemporánea",
    category: "Artesanía",
    location: "Masaya",
    department: "Masaya",
    description: "Transformamos técnicas tradicionales en piezas decorativas y regalos con identidad nicaragüense.",
    skills: ["Madera", "Cuero", "Personalizados"],
    rating: 4.7,
    reviews: 15,
    verified: true,
    available: true,
    initials: "TG",
    accent: "linear-gradient(135deg, #102c4c, #557899)",
    mapPosition: { x: 59, y: 61 },
    coordinates: { lat: 11.97444, lng: -86.09417 },
  },
  {
    id: 6,
    kind: "persona",
    name: "Samuel Pérez",
    role: "Barbero profesional",
    category: "Servicios",
    location: "Matagalpa",
    department: "Matagalpa",
    description: "Cortes modernos, asesoría de imagen y servicio para eventos. Atención con reserva y a domicilio.",
    skills: ["Barbería", "Imagen", "A domicilio"],
    rating: 4.9,
    reviews: 36,
    verified: true,
    available: true,
    initials: "SP",
    accent: "linear-gradient(135deg, #071b34, #386288)",
    mapPosition: { x: 60, y: 36 },
    coordinates: { lat: 12.92559, lng: -85.91747 },
  },
  {
    id: 7,
    kind: "negocio",
    name: "Mar Azul Studio",
    role: "Producción audiovisual",
    category: "Fotografía",
    location: "Rivas",
    department: "Rivas",
    description: "Contenido audiovisual para turismo, hoteles y marcas que quieren comunicar desde el Pacífico de Nicaragua.",
    skills: ["Drone", "Video", "Edición"],
    rating: 4.8,
    reviews: 20,
    verified: true,
    available: true,
    initials: "MA",
    accent: "linear-gradient(135deg, #08223c, #2f6da1)",
    mapPosition: { x: 62, y: 78 },
    coordinates: { lat: 11.43716, lng: -85.82632 },
  },
  {
    id: 8,
    kind: "negocio",
    name: "Nica Digital Lab",
    role: "Marketing & contenido",
    category: "Tecnología",
    location: "Chinandega",
    department: "Chinandega",
    description: "Ayudamos a pequeños negocios a vender mejor con estrategia digital, contenido y campañas medibles.",
    skills: ["Marketing", "Contenido", "Ads"],
    rating: 4.8,
    reviews: 27,
    verified: true,
    available: true,
    initials: "ND",
    accent: "linear-gradient(135deg, #0a2038, #3f6f98)",
    mapPosition: { x: 21, y: 42 },
    coordinates: { lat: 12.62937, lng: -87.13105 },
  },
];

export const stats = [
  { value: "17", label: "departamentos para conectar" },
  { value: "1", label: "vitrina digital para crecer" },
  { value: "2", label: "lados de una misma oportunidad" },
];
