import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Building2, Search, UsersRound } from "lucide-react";

export const metadata: Metadata = { title: "Para empresas" };

export default function EmpresasPage() {
  return (
    <main>
      <section className="page-hero page-hero-business"><div className="shell"><span className="eyebrow">GERMINA PARA EMPRESAS</span><h1>Publicá oportunidades y encontrá talento local con contexto.</h1><p>Las empresas verificadas cuentan con un perfil público, panel de vacantes, postulaciones y contacto directo con candidatos.</p><div className="hero-actions"><Link href="/crear-perfil" className="btn btn-primary btn-lg">Registrar empresa <ArrowRight size={18} /></Link><Link href="/descubrir" className="btn btn-ghost btn-lg">Ver vacantes y empresas</Link></div></div></section>
      <section className="section"><div className="shell"><div className="section-head split-head"><div><span className="eyebrow">UN FLUJO DE CONTRATACIÓN DENTRO DE GERMINA</span><h2>De la verificación empresarial a la primera postulación.</h2></div><p>Administración valida la empresa antes de habilitar la publicación de vacantes. Una vez aprobada, el equipo empresarial controla todo desde “Mi empresa”.</p></div><div className="value-grid"><article><span><BadgeCheck size={22} /></span><h3>Empresa verificada</h3><p>Expediente privado, revisión administrativa y perfil empresarial público una vez aprobado.</p></article><article><span><BriefcaseBusiness size={22} /></span><h3>Vacantes profesionales</h3><p>Creá, pausá y cerrá oportunidades con modalidad, requisitos, salario y beneficios.</p></article><article><span><UsersRound size={22} /></span><h3>Postulaciones organizadas</h3><p>Revisá candidatos por vacante, abrí su perfil y contactalos mediante los datos compartidos.</p></article></div></div></section>
      <section className="section section-soft"><div className="shell business-page-grid"><div className="business-copy"><span className="eyebrow">TALENTO LOCAL</span><h2>Buscá antes, durante y después de publicar.</h2><div className="business-feature"><Search size={20} /><div><strong>Directorio segmentado</strong><p>Talentos, emprendimientos y empresas viven en categorías distintas para facilitar la exploración.</p></div></div><div className="business-feature"><Building2 size={20} /><div><strong>Perfil corporativo</strong><p>Cada vacante conecta con el perfil público de la empresa para dar contexto y confianza.</p></div></div><div className="business-feature"><BadgeCheck size={20} /><div><strong>Control administrativo</strong><p>Germina puede aprobar empresas, cerrar vacantes y destacar oportunidades desde el panel general.</p></div></div></div><div className="company-demo-panel"><div className="company-demo-head"><Building2 size={21} /><div><strong>Mi empresa</strong><span>Panel privado empresarial</span></div></div><article className="company-result"><div className="talent-avatar talent-avatar-small"><BriefcaseBusiness size={18} /></div><div><strong>Vacantes activas</strong><span>Publicación, pausa y cierre</span></div><b>✓</b></article><article className="company-result"><div className="talent-avatar talent-avatar-small"><UsersRound size={18} /></div><div><strong>Postulaciones</strong><span>Seguimiento por candidato</span></div><b>✓</b></article><article className="company-result"><div className="talent-avatar talent-avatar-small"><BadgeCheck size={18} /></div><div><strong>Perfil verificado</strong><span>Visible en Descubrir</span></div><b>✓</b></article></div></div></section>
      <section className="section"><div className="shell business-cta"><div><span className="eyebrow">EMPEZÁ AHORA</span><h2>Creá la cuenta empresarial y enviá tu solicitud.</h2><p>Podrás completar la información y subir documentos mientras administración realiza la revisión.</p></div><Link href="/crear-perfil" className="btn btn-primary">Crear cuenta empresarial <ArrowRight size={16} /></Link></div></section>
    </main>
  );
}
